version: "3.9"

services:
  bot:
    build: .
    container_name: discord-utility-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app
    command: npm run dev

  mysql:
    image: mysql:8.3
    container_name: discord-bot-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discord_bot
      MYSQL_USER: bot
      MYSQL_PASSWORD: botpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
