apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitarashi-bot
  namespace: ibuki-mitarashi-bot
  labels:
    app: mitarashi-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitarashi-bot
  template:
    metadata:
      labels:
        app: mitarashi-bot
    spec:
      containers:
        - name: bot
          image: kemar1/mitarashi-bot:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: mitarashi-bot
            - configMapRef:
                name: mitarashi-bot-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
