apiVersion: v1
kind: Pod
metadata:
  name: prisma-migrate-once
  namespace: ibuki-mitarashi-bot
spec:
  restartPolicy: Never
  containers:
    - name: migrate
      image: kemar1/mitarashi-bot:latest   # いつも使っている本番用イメージ
      command: ["sh", "-c"]
      args:
        - npx prisma migrate resolve --applied 20250101000000_init &&
          npx prisma migrate deploy
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mitarashi-bot
              key: DATABASE_URL
