apiVersion: v1
kind: Service
metadata:
  name: mitarashi-bot
  namespace: ibuki-mitarashi-bot
  labels:
    app: mitarashi-bot
spec:
  selector:
    app: mitarashi-bot
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
  type: ClusterIP
