apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-utility-bot
  namespace: argocd
spec:
  destination:
    namespace: discord-bots
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/your-org/discord-utility-bot.git
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
