apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mitarashi-bot
  namespace: argocd
spec:
  destination:
    namespace: ibuki-mitarashi-bot
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ibuki-hum4/mitarashi-bot.git
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
